name = "SeisDvv"
uuid = "7496752f-774b-4904-a0f2-f9837ec78c00"
authors = ["Tim Clements <thclements@g.harvard.edu>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
SeisNoise = "8cc7c3c0-6b5d-11e9-39fe-c9cd0236e08b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
